/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_adaptivellm_runtime_services_GPUMemoryService */

#ifndef _Included_com_adaptivellm_runtime_services_GPUMemoryService
#define _Included_com_adaptivellm_runtime_services_GPUMemoryService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_adaptivellm_runtime_services_GPUMemoryService
 * Method:    initializeGPU
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_adaptivellm_runtime_services_GPUMemoryService_initializeGPU
  (JNIEnv *, jobject);

/*
 * Class:     com_adaptivellm_runtime_services_GPUMemoryService
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_adaptivellm_runtime_services_GPUMemoryService_shutdown
  (JNIEnv *, jobject);

/*
 * Class:     com_adaptivellm_runtime_services_GPUMemoryService
 * Method:    nativeAllocateGPU
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_adaptivellm_runtime_services_GPUMemoryService_nativeAllocateGPU
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_adaptivellm_runtime_services_GPUMemoryService
 * Method:    nativeFreeGPU
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_adaptivellm_runtime_services_GPUMemoryService_nativeFreeGPU
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_adaptivellm_runtime_services_GPUMemoryService
 * Method:    nativeGetSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_adaptivellm_runtime_services_GPUMemoryService_nativeGetSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_adaptivellm_runtime_services_GPUMemoryService
 * Method:    nativeMemcpyHostToDevice
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_adaptivellm_runtime_services_GPUMemoryService_nativeMemcpyHostToDevice
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_adaptivellm_runtime_services_GPUMemoryService
 * Method:    nativeMemcpyDeviceToHost
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_adaptivellm_runtime_services_GPUMemoryService_nativeMemcpyDeviceToHost
  (JNIEnv *, jobject, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
