/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_adaptivellm_runtime_GGUFModelLoader */

#ifndef _Included_com_adaptivellm_runtime_GGUFModelLoader
#define _Included_com_adaptivellm_runtime_GGUFModelLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_adaptivellm_runtime_GGUFModelLoader
 * Method:    nativeLoadModelGGUF
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_adaptivellm_runtime_GGUFModelLoader_nativeLoadModelGGUF
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_adaptivellm_runtime_GGUFModelLoader
 * Method:    nativeLoadLayerFromGGUF
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_adaptivellm_runtime_GGUFModelLoader_nativeLoadLayerFromGGUF
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_adaptivellm_runtime_GGUFModelLoader
 * Method:    nativeGetMetadata
 * Signature: ()Lcom/adaptivellm/runtime/GGUFModelLoader/ModelMetadata;
 */
JNIEXPORT jobject JNICALL Java_com_adaptivellm_runtime_GGUFModelLoader_nativeGetMetadata
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
