/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_adaptivellm_runtime_services_KVCacheGPUManager */

#ifndef _Included_com_adaptivellm_runtime_services_KVCacheGPUManager
#define _Included_com_adaptivellm_runtime_services_KVCacheGPUManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_adaptivellm_runtime_services_KVCacheGPUManager
 * Method:    initializeKVCache
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_adaptivellm_runtime_services_KVCacheGPUManager_initializeKVCache
  (JNIEnv *, jobject);

/*
 * Class:     com_adaptivellm_runtime_services_KVCacheGPUManager
 * Method:    shutdownKVCache
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_adaptivellm_runtime_services_KVCacheGPUManager_shutdownKVCache
  (JNIEnv *, jobject);

/*
 * Class:     com_adaptivellm_runtime_services_KVCacheGPUManager
 * Method:    nativeTransferToGPU
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_com_adaptivellm_runtime_services_KVCacheGPUManager_nativeTransferToGPU
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_adaptivellm_runtime_services_KVCacheGPUManager
 * Method:    nativeTransferFromGPU
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_adaptivellm_runtime_services_KVCacheGPUManager_nativeTransferFromGPU
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_adaptivellm_runtime_services_KVCacheGPUManager
 * Method:    nativeMarkPageUsed
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_adaptivellm_runtime_services_KVCacheGPUManager_nativeMarkPageUsed
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_adaptivellm_runtime_services_KVCacheGPUManager
 * Method:    nativeGetUsedMemory
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_adaptivellm_runtime_services_KVCacheGPUManager_nativeGetUsedMemory
  (JNIEnv *, jobject);

/*
 * Class:     com_adaptivellm_runtime_services_KVCacheGPUManager
 * Method:    nativeEvictLRU
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_adaptivellm_runtime_services_KVCacheGPUManager_nativeEvictLRU
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
