/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_adaptivellm_nativeengine_NativeEngine */

#ifndef _Included_com_adaptivellm_nativeengine_NativeEngine
#define _Included_com_adaptivellm_nativeengine_NativeEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_adaptivellm_nativeengine_NativeEngine
 * Method:    startRuntime
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_adaptivellm_nativeengine_NativeEngine_startRuntime
  (JNIEnv *, jobject);

/*
 * Class:     com_adaptivellm_nativeengine_NativeEngine
 * Method:    stopRuntime
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_adaptivellm_nativeengine_NativeEngine_stopRuntime
  (JNIEnv *, jobject);

/*
 * Class:     com_adaptivellm_nativeengine_NativeEngine
 * Method:    requestLayer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_adaptivellm_nativeengine_NativeEngine_requestLayer
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
