/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_adaptivellm_runtime_monitoring_GPUProfiler */

#ifndef _Included_com_adaptivellm_runtime_monitoring_GPUProfiler
#define _Included_com_adaptivellm_runtime_monitoring_GPUProfiler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_adaptivellm_runtime_monitoring_GPUProfiler
 * Method:    nativeGetGPUMemoryUsed
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_adaptivellm_runtime_monitoring_GPUProfiler_nativeGetGPUMemoryUsed
  (JNIEnv *, jobject);

/*
 * Class:     com_adaptivellm_runtime_monitoring_GPUProfiler
 * Method:    nativeGetGPUMemoryTotal
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_adaptivellm_runtime_monitoring_GPUProfiler_nativeGetGPUMemoryTotal
  (JNIEnv *, jobject);

/*
 * Class:     com_adaptivellm_runtime_monitoring_GPUProfiler
 * Method:    nativeGetGPUTemperature
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_adaptivellm_runtime_monitoring_GPUProfiler_nativeGetGPUTemperature
  (JNIEnv *, jobject);

/*
 * Class:     com_adaptivellm_runtime_monitoring_GPUProfiler
 * Method:    nativeGetGPUPowerDraw
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_adaptivellm_runtime_monitoring_GPUProfiler_nativeGetGPUPowerDraw
  (JNIEnv *, jobject);

/*
 * Class:     com_adaptivellm_runtime_monitoring_GPUProfiler
 * Method:    nativeGetMemoryBandwidth
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_adaptivellm_runtime_monitoring_GPUProfiler_nativeGetMemoryBandwidth
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
