/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_adaptivellm_runtime_ErrorRecoveryManager */

#ifndef _Included_com_adaptivellm_runtime_ErrorRecoveryManager
#define _Included_com_adaptivellm_runtime_ErrorRecoveryManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_adaptivellm_runtime_ErrorRecoveryManager
 * Method:    nativeCreateCheckpoint
 * Signature: (Ljava/lang/String;Lcom/adaptivellm/runtime/ErrorRecoveryManager/CheckpointData;)V
 */
JNIEXPORT void JNICALL Java_com_adaptivellm_runtime_ErrorRecoveryManager_nativeCreateCheckpoint
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_adaptivellm_runtime_ErrorRecoveryManager
 * Method:    nativeRecoverCheckpoint
 * Signature: (Ljava/lang/String;)Lcom/adaptivellm/runtime/ErrorRecoveryManager/CheckpointData;
 */
JNIEXPORT jobject JNICALL Java_com_adaptivellm_runtime_ErrorRecoveryManager_nativeRecoverCheckpoint
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
