/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_adaptivellm_runtime_ModelValidator */

#ifndef _Included_com_adaptivellm_runtime_ModelValidator
#define _Included_com_adaptivellm_runtime_ModelValidator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_adaptivellm_runtime_ModelValidator
 * Method:    nativeValidateModel
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_adaptivellm_runtime_ModelValidator_nativeValidateModel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_adaptivellm_runtime_ModelValidator
 * Method:    nativeCheckGPU
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_adaptivellm_runtime_ModelValidator_nativeCheckGPU
  (JNIEnv *, jobject);

/*
 * Class:     com_adaptivellm_runtime_ModelValidator
 * Method:    nativeGetGPUMemory
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_adaptivellm_runtime_ModelValidator_nativeGetGPUMemory
  (JNIEnv *, jobject);

/*
 * Class:     com_adaptivellm_runtime_ModelValidator
 * Method:    nativeGetComputeCapability
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_adaptivellm_runtime_ModelValidator_nativeGetComputeCapability
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
