/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_adaptivellm_scheduler_Phase2NativeEngineAdapter */

#ifndef _Included_com_adaptivellm_scheduler_Phase2NativeEngineAdapter
#define _Included_com_adaptivellm_scheduler_Phase2NativeEngineAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_adaptivellm_scheduler_Phase2NativeEngineAdapter
 * Method:    nativeStart
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_adaptivellm_scheduler_Phase2NativeEngineAdapter_nativeStart
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_adaptivellm_scheduler_Phase2NativeEngineAdapter
 * Method:    nativeStop
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_adaptivellm_scheduler_Phase2NativeEngineAdapter_nativeStop
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_adaptivellm_scheduler_Phase2NativeEngineAdapter
 * Method:    nativePrefetchLayer
 * Signature: (Ljava/lang/Object;I)J
 */
JNIEXPORT jlong JNICALL Java_com_adaptivellm_scheduler_Phase2NativeEngineAdapter_nativePrefetchLayer
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_adaptivellm_scheduler_Phase2NativeEngineAdapter
 * Method:    nativeEvictLayer
 * Signature: (Ljava/lang/Object;I)J
 */
JNIEXPORT jlong JNICALL Java_com_adaptivellm_scheduler_Phase2NativeEngineAdapter_nativeEvictLayer
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_adaptivellm_scheduler_Phase2NativeEngineAdapter
 * Method:    nativeKeepLayer
 * Signature: (Ljava/lang/Object;I)J
 */
JNIEXPORT jlong JNICALL Java_com_adaptivellm_scheduler_Phase2NativeEngineAdapter_nativeKeepLayer
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_adaptivellm_scheduler_Phase2NativeEngineAdapter
 * Method:    nativeMoveKvToRam
 * Signature: (Ljava/lang/Object;J)J
 */
JNIEXPORT jlong JNICALL Java_com_adaptivellm_scheduler_Phase2NativeEngineAdapter_nativeMoveKvToRam
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     com_adaptivellm_scheduler_Phase2NativeEngineAdapter
 * Method:    nativeMoveKvToGpu
 * Signature: (Ljava/lang/Object;J)J
 */
JNIEXPORT jlong JNICALL Java_com_adaptivellm_scheduler_Phase2NativeEngineAdapter_nativeMoveKvToGpu
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     com_adaptivellm_scheduler_Phase2NativeEngineAdapter
 * Method:    nativeCompressKv
 * Signature: (Ljava/lang/Object;J)J
 */
JNIEXPORT jlong JNICALL Java_com_adaptivellm_scheduler_Phase2NativeEngineAdapter_nativeCompressKv
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     com_adaptivellm_scheduler_Phase2NativeEngineAdapter
 * Method:    nativeOffloadKv
 * Signature: (Ljava/lang/Object;J)J
 */
JNIEXPORT jlong JNICALL Java_com_adaptivellm_scheduler_Phase2NativeEngineAdapter_nativeOffloadKv
  (JNIEnv *, jobject, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
