/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_adaptivellm_scheduler_ProductionMemoryStateProvider */

#ifndef _Included_com_adaptivellm_scheduler_ProductionMemoryStateProvider
#define _Included_com_adaptivellm_scheduler_ProductionMemoryStateProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_adaptivellm_scheduler_ProductionMemoryStateProvider
 * Method:    getCurrentLayerNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_adaptivellm_scheduler_ProductionMemoryStateProvider_getCurrentLayerNative
  (JNIEnv *, jobject);

/*
 * Class:     com_adaptivellm_scheduler_ProductionMemoryStateProvider
 * Method:    getGpuMemoryNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_adaptivellm_scheduler_ProductionMemoryStateProvider_getGpuMemoryNative
  (JNIEnv *, jobject);

/*
 * Class:     com_adaptivellm_scheduler_ProductionMemoryStateProvider
 * Method:    getKvPagesNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_adaptivellm_scheduler_ProductionMemoryStateProvider_getKvPagesNative
  (JNIEnv *, jobject);

/*
 * Class:     com_adaptivellm_scheduler_ProductionMemoryStateProvider
 * Method:    getCachedLayersNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_adaptivellm_scheduler_ProductionMemoryStateProvider_getCachedLayersNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
